### ISSUE TITLE
Errors in tutorial

### ISSUE THREAD

**Issue by OliverCole** [metatypedev/metatype#404]
Followed tutorial:
```
[ERROR] Failed to load typegraph(s) from "api/example.py": error while loading typegraph(s) from "/home/oli/metatype/demo/api/example.py":   File "/home/oli/metatype/demo/api/example.py", line 8
[ERROR]>     ) as g:
[ERROR]>     ^
[ERROR]> SyntaxError: unmatched ')'
```

Changed code to:
```python
  ) as g:
  # declare runtimes and policies
```

Now I get:
```
[ERROR] Failed to load typegraph(s) from "api/example.py": error while loading typegraph(s) from "/home/oli/metatype/demo/api/example.py": Traceback (most recent call last):
[ERROR]>   File "/home/oli/metatype/demo/api/example.py", line 4, in <module>
[ERROR]>     with TypeGraph(
[ERROR]> TypeError: TypeGraph.__init__() got an unexpected keyword argument 'allow_origin'
```

**Comment by OliverCole** [comment]
Thanks, now on to:

```
[ERROR] Error while pushing typegraph database: query failed:  - unsupported provider: postgres
```

Did I miss something to install the provider?

**Comment by zifeo** [comment]
@OliverCole try with:
```
      TG_DATABASE_POSTGRES_CONN: postgresql://postgres:password@postgres:5432/db
```

**Comment by OliverCole** [comment]
That was it, thanks!
